services: 
  backend-api-prod:
    profiles:
      - prod
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
      target: prod
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network-dev 

  backend-api-dev:
    profiles:
      - dev
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.dev
      target: dev
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app # This has to be the same path as the WORKDIR in the Dockerfile
      - /usr/src/app/node_modules
    develop:
      watch:
        - path: ./backend/src
          target: /usr/src/app/src # Target needs to be the route inside the container
          action: sync
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    networks:
      - app-network-dev  

  react-frontend-prod:
    profiles:
      - prod
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      target: prod
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    networks:
      - app-network-dev 
    depends_on:
      - backend-api-prod

  react-frotend-dev:
    profiles:
      - dev
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.dev
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # This has to be the same path as the WORKDIR in the Dockerfile
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - app-network-dev 
    depends_on:
      - backend-api-dev # This forces backend to start first
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/package.json
          action: rebuild     

networks:
  app-network-dev:
    driver: bridge